// <auto-generated />
using ConstructionApi.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ConstructionApi.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260704124613_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.4");

            modelBuilder.Entity("ConstructionApi.Models.PriceList", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("CatalogAuthor")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("CatalogCode")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("CatalogDescription")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("CatalogVersion")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("EquipmentPercentage")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("LabourPercentage")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("MaterialPercentage")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Price")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("SafetyPercentage")
                        .HasColumnType("TEXT");

                    b.Property<string>("Subcategory")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("UnitOfMeasure")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("PriceLists");
                });
#pragma warning restore 612, 618
        }
    }
}
